version: '3.8'
services:
  nginx:
    build: ./nginx
    restart: always
    depends_on:
      - frontend
      - backend
    ports:
      - '80:80'
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
  backend:
    build: ./backend
    ports:
      - '8000:8000'
